### ISSUE TITLE
Fatal exception when input is not a int

### ISSUE THREAD

**Issue by CrispyXYZ** [JvavscriptDEV/java-JvavScipt#1]
Console i/o:
```js
JvavScript>a
Exception in thread "main" java.util.InputMismatchException
        at java.base/java.util.Scanner.throwFor(Scanner.java:939)
        at java.base/java.util.Scanner.next(Scanner.java:1594)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
        at main.JvavScriptmain.main(JvavScriptmain.java:15)
```

**Comment by ChengT-cmd** [comment]
We are trying fix the bug in a few weeks, but :
We are not going to make a really script that called "JvavScript" in Java, So this repo PROBELY won't been update in the future.

Oh, God! Bless me in advance for not deleting the IDE 🔢

**Comment by ChengT-cmd** [comment]
Fixed the bug. Go the newest release for more info.  
[https://github.com/JvavscriptDEV/java-JvavScipt/releases/tag/2.0.0](https://github.com/JvavscriptDEV/java-JvavScipt/releases/tag/2.0.0)

**Comment by CrispyXYZ** [comment]
Wow, thx bro!
